### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by zengcanxiang** [bboylin/FatJar#1]
虽然没有用到贵开源库，但是觉得可能会有这么一种需求，合并的module可能是不确定的，可以提供在命令行输入的功能。两者并存

**Comment by bboylin** [comment]
命令行输入的话module比较多的时候每打一次包都要一遍一遍输入多个module名太麻烦了。module名在fatJarExt里的paths中可以修改或者添加的，个人觉得比命令行方便一点。

**Comment by fenghebaiyang** [comment]
你好，如果module中包含资源文件，这种方案也可行吗？

**Comment by bboylin** [comment]
资源文件和so无法打入jar包，AAR可以。如果非要打入jar包可以放到assets下，通过代码去获取，1.0.3版本开始可以打入module的assets，但是资源文件和so不支持。
